spring.application.name=CentroVecinal

server.port=${SERVER_PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3307/centro_vecinal}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cv_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cv_pass}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080/realms/centro-vecinal}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8080/realms/centro-vecinal/protocol/openid-connect/certs}
spring.security.oauth2.resourceserver.jwt.audiences=account

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

app.attachments.storage-path=${APP_ATTACHMENTS_STORAGE_PATH:uploads}

app.keycloak.admin.base-url=${APP_KEYCLOAK_ADMIN_BASE_URL:http://localhost:8080}
app.keycloak.admin.realm=${APP_KEYCLOAK_ADMIN_REALM:centro-vecinal}
app.keycloak.admin.client-id=${APP_KEYCLOAK_ADMIN_CLIENT_ID:backend-admin-cli}
app.keycloak.admin.client-secret=${APP_KEYCLOAK_ADMIN_CLIENT_SECRET:change-me}
